# Generated by Django 2.0.5 on 2018-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalgroup',
            name='slug',
            field=models.SlugField(help_text='A short label, generally used in URLs', max_length=70, unique=True),
        ),
    ]
