# Generated by Django 2.0.5 on 2018-08-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180808_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalgroup',
            options={},
        ),
    ]
