# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(db_index=True, max_length=200)),
                ('surname', models.CharField(db_index=True, max_length=200)),
                ('consulting_room', models.IntegerField(default=0)),
                ('employee', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('surname',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_specialization', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='A short label, generally used in URLs', max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='medical',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='medical_visit.Specialization'),
        ),
    ]
