# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='consulting_room',
            field=models.IntegerField(unique=True),
        ),
    ]
