# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0003_medicalvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalvisit',
            name='date_of_visit',
            field=models.DateField(null=True),
        ),
    ]
