# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0004_auto_20171207_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalvisit',
            old_name='time_of_visit',
            new_name='hour_of_visit',
        ),
    ]
