# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0006_auto_20171212_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='employee',
            new_name='presence',
        ),
    ]
