# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0007_auto_20171221_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('type_of_specialization',)},
        ),
    ]
