# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0008_auto_20171221_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='nickname',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medical',
            name='forename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medical',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
