# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0009_auto_20171226_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
