# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0010_medical_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical',
            options={'ordering': ('surname', 'specialization')},
        ),
    ]
