# Generated by Django 2.0.5 on 2018-08-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0015_auto_20180808_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_visit.Specialization'),
        ),
    ]
