# Generated by Django 2.0.5 on 2018-08-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0016_auto_20180809_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_visit.Specialization'),
        ),
    ]
