# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_visit', '0012_auto_20171226_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAdviceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('prescription_drugs', models.TextField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='medical_visit.MedicalVisit')),
            ],
        ),
    ]
