# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_advice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaladvicedescription',
            old_name='prescription_drugs',
            new_name='recommendations',
        ),
    ]
