# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_advice', '0002_auto_20171231_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaladvicedescription',
            name='prescribed_medicines',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
