# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_advice', '0003_medicaladvicedescription_prescribed_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaladvicedescription',
            name='discount',
            field=models.CharField(default='100%', max_length=5),
        ),
    ]
