# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_advice', '0004_medicaladvicedescription_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaladvicedescription',
            name='antibiotic',
            field=models.BooleanField(default=False),
        ),
    ]
